export default [
  ["Apple", "Pear"],
  ["Orange", "Mandarin"],
  ["Pizza", "Calzone"],
  ["Burger", "Sandwich"],
  ["Taco", "Burrito"],
  ["Sushi", "Sashimi"],
  ["Steak", "Roast"],
  ["Bacon", "Pancetta"],
  ["Coffee", "Latte"],
  ["Tea", "Chai"],
  ["Lemonade", "Iced Tea"],
  ["Milk", "Cream"],
  ["Water", "Juice"],
  ["Beer", "Ale"],
  ["Wine", "Champagne"],
  ["Pancake", "Waffle"],
  ["Donut", "Bagel"],
  ["Muffin", "Cupcake"],
  ["Ice cream", "Gelato"],
  ["Yogurt", "Pudding"],
  ["Spaghetti", "Noodles"],
  ["Rice", "Quinoa"],
  ["Bread", "Toast"],
  ["Cheese", "Butter"],
  ["Salt", "Pepper"],
  ["Sugar", "Honey"],
  ["Salad", "Coleslaw"],
  ["Chips", "Fries"],
  ["Biscuit", "Cookie"],
  ["Cake", "Pie"],
  ["Chocolate", "Cocoa"],
  ["Candy", "Gummy"],
  ["Soup", "Stew"],
  ["Sauce", "Gravy"],
  ["Jam", "Jelly"],
  ["Butter", "Margarine"],
  ["Cereal", "Oatmeal"],
  ["Meat", "Poultry"],
  ["Fish", "Seafood"],
  ["Chicken", "Turkey"],
  ["Duck", "Goose"],
  ["Lamb", "Mutton"],
  ["Pork", "Ham"],
  ["Onion", "Garlic"],
  ["Potato", "Sweet Potato"],
  ["Carrot", "Radish"],
  ["Tomato", "Bell Pepper"],
  ["Cucumber", "Zucchini"],
  ["Lettuce", "Cabbage"],
  ["Spinach", "Kale"],
];
