export default [
  ["Momo", "Yomari"],
  ["Momo", "Chowmein"],
  ["Momo", "Idli"],
  ["Sel Roti", "Puri"],
  ["Sel Roti", "Donut"],
  ["Sel Roti", "Begal"],
  ["Sel Roti", "Nimki"],
  ["Dal Bhat", "Masu Bhat"],
  ["Dal Bhat", "Gundruk"],
  ["Dal Bhat", "Chowmein"],
  ["Dal Bhat", "Momo"],
  ["Lassi", "Chiya"],
  ["Lassi", "Mocha"],
  ["Lassi", "Chyang"],
  ["Thukpa", "Ramen"],
  ["Thukpa", "Chowmein"],
  ["Thukpa", "Wai Wai"],
  ["Chowmein", "Wai Wai"],
  ["Chow Chow", "Wai Wai"],
  ["Chow Chow", "Noodles"],
  ["Chow Chow", "Maggi"],
  ["Wai Wai", "Maggi"],
  ["Doko", "Nanglo"],
  ["Doko", "Basket"],
  ["Violin", "Sarangi"],
  ["Guitar", "Sarangi"],
  ["Guitar", "Sitar"],
  ["Kadai", "Tapke"],
  ["Buff Momo", "Veg Momo"],
  ["Police", "Mama"],
  ["Juju Dhau", "Curd"],
  ["Tabla", "Madal"],
  ["Bhai Tika", "Raksha Bandhan"],
  ["Trekking", "Hiking"],
  ["Samosa", "Pakoda"],
  ["Kavre", "Kavreli Samdhi"],
  ["Kukur", "Biralo"],
  ["Aaila", "Raksi"],
  ["Chyang", "Aaila"],
  ["Chappal", "Jutta"],
  ["Jhapa", "Terai"],
  ["Jhapali", "Syangjali"],
  ["Yamraj", "Truck"],
  ["Excavator", "Bulldozer"],
  ["Neta", "Bhrasthachar"],
  ["Oli", "Bhrasthachar"],
  ["Oli", "Neta"],
  ["Oli", "Prachanda"],
  ["Bihar", "India"],
  ["Terai", "India"],
  ["Newar", "Tamang"],
  ["Newar", "Tharu"],
  ["Tamang", "Tharu"],
  ["Loshar", "Jatra"],
  ["Chatpate", "Pani Puri"],
  ["Chatpate", "Aloo Nimki"],
  ["Samosa Chat", "Aloo Nimki"],
  ["Samosa Chat", "Pani Puri"],
  ["Harka Sampang", "Balen Shah"],
  ["Vim", "Dhoni"],
  ["Ring Road", "Traffic Jam"],
  ["Pathao", "InDrive"],
  ["Khalti", "Esewa"],
  ["Microbus", "Tempo"],
  ["Visa", "Australia"],
  ["Visa", "Password"],
  ["Bahun", "Newar"],
  ["Mutton", "Meat"],
];
