export default [
  ["Star Wars", "Star Trek"],
  ["Marvel", "DC"],
  ["Harry Potter", "Lord of the Rings"],
  ["Game of Thrones", "House of the Dragon"],
  ["Breaking Bad", "Better Call Saul"],
  ["Friends", "Seinfeld"],
  ["The Office", "Parks and Rec"],
  ["Mario", "Sonic"],
  ["Zelda", "Final Fantasy"],
  ["Fortnite", "PUBG"],
  ["Minecraft", "Roblox"],
  ["Taylor Swift", "Beyoncé"],
  ["Michael Jackson", "Prince"],
  ["The Beatles", "The Rolling Stones"],
  ["Rock", "Heavy Metal"],
  ["Pop", "R&B"],
  ["Rap", "Hip Hop"],
  ["Jazz", "Blues"],
  ["Tom Cruise", "Tom Hanks"],
  ["Leonardo DiCaprio", "Brad Pitt"],
  ["Dwayne Johnson", "Jason Statham"],
  ["Will Smith", "Eddie Murphy"],
  ["James Bond", "Jason Bourne"],
  ["Mission Impossible", "The Matrix"],
  ["Avatar", "Titanic"],
  ["Toy Story", "Finding Nemo"],
  ["The Lion King", "Aladdin"],
  ["Frozen", "Moana"],
  ["Pokémon", "Digimon"],
  ["Dragon Ball Z", "Naruto"],
  ["One Piece", "Bleach"],
  ["The Simpsons", "Family Guy"],
  ["SpongeBob", "Hey Arnold!"],
  ["Barbie", "Bratz"],
  ["Lego", "Playmobil"],
  ["G.I. Joe", "Transformers"],
  ["Hot Wheels", "Matchbox"],
  [" Monopoly", "Scrabble"],
  ["Clue", "Risk"],
  ["Dungeons & Dragons", "Pathfinder"],
  ["Magic: The Gathering", "Yu-Gi-Oh!"],
  ["Nintendo", "Sega"],
  ["PlayStation", "Xbox"],
  ["Netflix", "Hulu"],
  ["Spotify", "Apple Music"],
  ["YouTube", "TikTok"],
  ["Instagram", "Snapchat"],
  ["Facebook", "Twitter"],
];
