export default [
  ["Dragon", "Wyvern"],
  ["Wizard", "Sorcerer"],
  ["Elf", "Fairy"],
  ["Dwarf", "Gnome"],
  ["Orc", "Goblin"],
  ["Vampire", "Werewolf"],
  ["Zombie", "Ghoul"],
  ["Ghost", "Spirit"],
  ["Unicorn", "Pegasus"],
  ["Mermaid", "Siren"],
  ["Troll", "Ogre"],
  ["Kraken", "Leviathan"],
  ["Cthulhu", "Azathoth"],
  ["Hobbit", "Gnome"],
  ["Gandalf", "Dumbledore"],
  ["Harry Potter", "Frodo"],
  ["Star Wars", "Dune"],
  ["Lord of the Rings", "The Hobbit"],
  ["Superman", "Captain America"],
  ["Batman", "Iron Man"],
  ["Spider-Man", "Venom"],
  ["Hulk", "Thor"],
  ["Wonder Woman", "Captain Marvel"],
  ["The Flash", "Quicksilver"],
  ["Doctor Who", "Star Trek"],
  ["The Matrix", "Blade Runner"],
  ["The Witcher", "Elden Ring"],
  ["Game of Thrones", "Vikings"],
  ["Narnia", "Middle-earth"],
  ["Atlantis", "El Dorado"],
  ["Voldemort", "Sauron"],
  ["Godzilla", "King Kong"],
  ["Frankenstein", "Dracula"],
  ["Sherlock Holmes", "Hercule Poirot"],
  ["Dr. Seuss", "Roald Dahl"],
  ["Peter Pan", "Pinocchio"],
  ["Cinderella", "Snow White"],
  ["Alice in Wonderland", "Through the Looking-Glass"],
  ["The Wizard of Oz", "The Phantom Tollbooth"],
  ["The Chronicles of Narnia", "The Golden Compass"],
  ["The Hunger Games", "Divergent"],
  ["Twilight", "Vampire Diaries"],
  ["Harry Potter", "Percy Jackson"],
  ["Magic", "Alchemy"],
  ["Potion", "Elixir"],
  ["Spell", "Curse"],
  ["Wand", "Staff"],
  ["Sword", "Excalibur"],
  ["Ring", "Amulet"],
  ["Crown", "Tiara"],
];
