export default [
  ["City", "Town"],
  ["Village", "Hamlet"],
  ["Country", "Nation"],
  ["Continent", "Subcontinent"],
  ["Island", "Archipelago"],
  ["Desert", "Oasis"],
  ["Forest", "Woodland"],
  ["River", "Estuary"],
  ["Lake", "Lagoon"],
  ["Ocean", "Gulf"],
  ["Mountain", "Peak"],
  ["Hill", "Ridge"],
  ["Volcano", "Crater"],
  ["Cave", "Cavern"],
  ["Waterfall", "Cascade"],
  ["Beach", "Shore"],
  ["Harbor", "Port"],
  ["Lighthouse", "Beacon"],
  ["Tower", "Spire"],
  ["Castle", "Fortress"],
  ["Palace", "Manor"],
  ["Bridge", "Viaduct"],
  ["Tunnel", "Underpass"],
  ["Statue", "Monument"],
  ["Fountain", "Geyser"],
  ["Eiffel Tower", "Statue of Liberty"],
  ["Colosseum", "Pantheon"],
  ["Pyramids", "Sphinx"],
  ["Great Wall", "Forbidden City"],
  ["Machu Picchu", "Chichen Itza"],
  ["Stonehenge", "Avebury"],
  ["Big Ben", "Tower Bridge"],
  ["Mount Everest", "K2"],
  ["Grand Canyon", "Niagara Falls"],
  ["Amazon River", "Nile River"],
  ["Sahara Desert", "Gobi Desert"],
  ["Great Barrier Reef", "Galapagos Islands"],
  ["Paris", "Rome"],
  ["London", "New York"],
  ["Tokyo", "Kyoto"],
  ["Beijing", "Shanghai"],
  ["Sydney", "Melbourne"],
  ["Cairo", "Luxor"],
  ["Athens", "Sparta"],
  ["Jerusalem", "Bethlehem"],
  ["Mecca", "Medina"],
  ["Vatican City", "Florence"],
];
