export default [
  ["Swimming", "Diving"],
  ["Skiing", "Snowboarding"],
  ["Bowling", "Billiards"],
  ["Golf", "Tennis"],
  ["Basketball", "Volleyball"],
  ["Football", "Soccer"],
  ["Running", "Jogging"],
  ["Climbing", "Hiking"],
  ["Fishing", "Hunting"],
  ["Camping", "Hiking"],
  ["Reading", "Writing"],
  ["Drawing", "Painting"],
  ["Photography", "Videography"],
  ["Gaming", "Streaming"],
  ["Cooking", "Baking"],
  ["Sewing", "Knitting"],
  ["Gardening", "Farming"],
  ["Singing", "Humming"],
  ["Dancing", "Ballet"],
  ["Playing guitar", "Playing piano"],
  ["Drumming", "Percussion"],
  ["Chess", "Checkers"],
  ["Poker", "Blackjack"],
  ["Scrabble", "Boggle"],
  ["Monopoly", "Risk"],
  ["Sudoku", "Crossword"],
  ["Puzzling", "Riddling"],
  ["Writing", "Journaling"],
  ["Reading", "Listening to a podcast"],
  ["Watching TV", "Watching a movie"],
  ["Listening to music", "Listening to a podcast"],
  ["Bicycling", "Motorcycling"],
  ["Skating", "Rollerblading"],
  ["Sailing", "Boating"],
  ["Surfing", "Bodyboarding"],
  ["Exploring", "Traveling"],
  ["Collecting", "Hoarding"],
  ["Exercising", "Working out"],
  ["Yoga", "Pilates"],
  ["Meditating", "Praying"],
  ["Sleeping", "Napping"],
];
