export default [
  ["Einstein", "Newton"],
  ["Shakespeare", "Marlowe"],
  ["Mozart", "Beethoven"],
  ["Mandela", "Gandhi"],
  ["Tesla", "Edison"],
  ["Churchill", "Roosevelt"],
  ["Picasso", "Dali"],
  ["Napoleon", "Caesar"],
  ["Lincoln", "Grant"],
  ["Fleming", "Pasteur"],
  ["Curie", "Franklin"],
  ["Obama", "Biden"],
  ["Hawking", "Sagan"],
  ["Jobs", "Wozniak"],
  ["DaVinci", "Michelangelo"],
  ["Columbus", "Magellan"],
  ["Gutenberg", "Edison"],
  ["Turing", "vonNeumann"],
  ["FDR", "Truman"],
  ["Freud", "Jung"],
  ["Mandela", "King"],
  ["QueenElizabeth", "Victoria"],
  ["Lincoln", "Jefferson"],
  ["Churchill", "Attlee"],
  ["Newton", "Galileo"],
  ["Beethoven", "Mozart"],
  ["Einstein", "Bohr"],
  ["Shakespeare", "Cervantes"],
  ["Galileo", "Kepler"],
  ["Franklin", "Jefferson"],
  ["Roosevelt", "Truman"],
  ["MartinLuther", "JohnCalvin"],
  ["Gandhi", "Tagore"],
  ["Newton", "Pascal"],
  ["Edison", "Bell"],
  ["Curie", "Boyle"],
  ["Tesla", "Marconi"],
  ["Hawking", "Feynman"],
  ["Jobs", "Gates"],
  ["Churchill", "DeGaulle"],
  ["Lincoln", "Grant"],
  ["Hitler", "Mussolini"],
  ["Stalin", "Lenin"],
  ["King", "Queen"],
  ["Cleopatra", "Nefertiti"],
  ["Alexander", "Cyrus"],
  ["Caesar", "Augustus"],
  ["Mozart", "Haydn"],
  ["Picasso", "Warhol"],
  ["Dali", "Magritte"],
  ["Michelangelo", "Donatello"],
  ["Abraham Lincoln", "George Washington"],
  ["Alexander the Great", "Julius Caesar"],
  ["Winston Churchill", "Franklin D. Roosevelt"],
  ["Napoleon Bonaparte", "Arthur Wellesley"],
  ["Mahatma Gandhi", "Jawaharlal Nehru"],
  ["William Shakespeare", "Charles Dickens"],
  ["Albert Einstein", "Isaac Newton"],
  ["Marie Curie", "Alexander Fleming"],
  ["Leonardo da Vinci", "Michelangelo Buonarroti"],
  ["Christopher Columbus", "Amerigo Vespucci"],
  ["Joan of Arc", "Mary Wollstonecraft"],
  ["Plato", "Aristotle"],
  ["Socrates", "Confucius"],
  ["Alexander the Great", "Attila the Hun"],
  ["Nikola Tesla", "Thomas Edison"],
  ["Abraham Lincoln", "Ulysses S. Grant"],
  ["Adolf Hitler", "Benito Mussolini"],
  ["Joseph Stalin", "Vladimir Lenin"],
  ["Cleopatra VII", "Nefertiti"],
  ["Queen Elizabeth I", "Queen Victoria"],
  ["Winston Churchill", "Harry S. Truman"],
  ["Nelson Mandela", "Mahatma Gandhi"],
  ["Galileo Galilei", "Johannes Kepler"],
  ["Isaac Newton", "Galileo Galilei"],
  ["George Washington", "Thomas Jefferson"],
  ["Marie Curie", "Marie Antoinette"],
  ["Benjamin Franklin", "Thomas Jefferson"],
  ["Julius Caesar", "Augustus Caesar"],
  ["Hammurabi", "Sargon of Akkad"],
  ["Leo Tolstoy", "Fyodor Dostoevsky"],
  ["Abraham Lincoln", "Andrew Johnson"],
  ["Leonardo da Vinci", "Raphael Sanzio"],
  ["Napoleon Bonaparte", "Josephine de Beauharnais"],
  ["Nelson Mandela", "Desmond Tutu"],
  ["Sigmund Freud", "Carl Jung"],
  ["Karl Marx", "Friedrich Engels"],
  ["Confucius", "Laozi"],
  ["Otto von Bismarck", "Helmuth von Moltke"],
  ["Galileo Galilei", "Nicolaus Copernicus"],
  ["Isaac Newton", "Blaise Pascal"],
  ["Homer", "Virgil"],
  ["Apollo", "Zeus"],
  ["Athena", "Hera"],
  ["Julius Caesar", "Marcus Junius Brutus"],
  ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven"],
  ["Winston Churchill", "Benjamin Disraeli"],
  ["Abraham Lincoln", "Samuel Curtis"],
  ["Albert Einstein", "Richard Feynman"],
  ["Genghis Khan", "Kublai Khan"],
  ["Attila the Hun", "Ögedei Khan"],
  ["Christopher Columbus", "John Cabot"],
  ["Ferdinand Magellan", "James Cook"],
  ["William Shakespeare", "John Milton"],
  ["Alexander the Great", "Philip II of Macedon"],
];
